TARGET_COMPANIES = [
    "Microsoft",
    "Amazon",
    "Google",
    "Meta",
    "Oracle",
    "Apple",
    "Adobe",
    "Snowflake",
    "Datadog",
    "HubSpot",
    "Stripe",
    "Visa",
    "Capital One",
    "JPMorgan Chase",
    "Citi",
    "American Express",
    "EY",
    "Deloitte",
    "PwC",
    "KPMG",
    "Accenture",
    "Cognizant",
    "Infosys",
    "TCS"
]